content/notes/config.md

just a minor fix in the config page.
and using this as an opportunity to say a huge thank you for creating this lovely thing! :heart: 
that's exactly what I was looking for!
(the only caveat is that we can't use [[wikilinks]], but all the other advantages makes it tollerable :slightly_smiling_face:)

fix custom.scss path

---

content/notes/obsidian.md

Hello 👋 This PR fixes a small typo on the Obsidian Vault Integration page.
---
Quartz is super neat! I love how customisable it is.

Fix typo: recomment -> recommend

---

assets/js/graph.js
assets/js/search.js
layouts/partials/graph.html
layouts/partials/head.html

Adds #109 
Currently, Quartz is a statically generated MPA, meaning that on each page navigation, everything must be reloaded. SPA's allow for more efficient page navigation, but Quartz cannot be practically designed as a SPA.
With this feature, Quartz gains SPA-like navigation, meaning faster pages with a cache and less JavaScript run upon subsequent navigations.
Demo: https://www.loom.com/share/ccd5429ddda04dfea882440b78ce61f2

Add router

---

assets/js/graph.js
data/config.yaml
layouts/partials/graph.html
layouts/partials/head.html

Fixes active node (red circle below) and changes it upon SPA page navigation

Fix active node on graph

---

assets/styles/custom.scss

Adds a custom progress bar color (set to `--secondary` by default)

Add support for progress bar color

---

layouts/partials/head.html

Hi again, sorry for the enormous amount of PR's today 😅. I was just glancing over the codebase to triple make sure there wasn't any issues caused by the new PR's and I forgot to add some handling logic for the non-spa fallback. 
Wondering if you could take a look and thanks for the patience in advance!

Fix non-spa fallback

---

data/config.yaml
layouts/partials/footer.html
layouts/partials/head.html

Some users may want to remove backlinks / graph. This allows users to toggle this in their config.

Add option to toggle footer

---

assets/js/graph.js
config.toml
data/graphConfig.yaml
layouts/index.html
layouts/partials/footerIndex.html
layouts/partials/head.html

Add options and ability to have a global graph on the home page, local graphs on subpage. Plus options : 
scale: 1
repelForce: 2
centerForce: 1
linkDistance: 1
fontSize: 0.6
opacityScale: 3
I had to comment out ``window.Million.prefetch(new URL(`${baseUrl}${decodeURI(d.id).replace(/\s+/g, "-")}/`))`` line 183 of graph.js, because the click on node was not working well and clicked as soon as hovered.
This [Vault](https://www.dhammacharts.org/vault/) shows a demo.
Thanks for this very nice Quartz !

Improve graph display ++ 

---

assets/js/router.js

Bump million to 1.11.3

---

assets/js/router.js

Fixes `width: 0` bug when diffing

Fix `width: auto` for SPA routing

---

assets/js/clipboard.js

minor fix to remove unnecessary logging.

fix: remove console log

---

content/notes/showcase.md

A website I made using Quartz that hosts lots of my sixth form work.

Add SethMB Work

---

i18n/es.toml

I created an `es.toml` file to add a Spanish translation.
Quartz is great! 🪴

feat: Add Spanish translation

---

content/notes/CJK + Latex Support (测试).md

great library! found this typo when I was exploring the libraries latex support.

fix euler's identity

---

i18n/fr.toml

I made a translation in french :)

Add French translation

---

content/notes/showcase.md

Pretty self-explanatory. Just adds a link to my Quartz to the showcase.

docs: add Abhijeet's math-wiki to the showcase

---

i18n/it.toml

Not done yet, I'll need to look deeper into i18n and HUGO, but it's a start

feat: Added italian localization in i18n/it.toml

---

i18n/no.toml

Added Norwegian localization.
Thanks for the brilliant work with Quartz.

feat: Added Norwegian localization

---

i18n/zh-cn.toml
layouts/partials/textprocessing.html

Hi! I created a simplified Chinese translation file for Quartz :)

feat: Added simplified Chinese translations

---

data/config.yaml

fix: fix misspelling

---

assets/js/clipboard.js
assets/js/code-title.js
assets/js/full-text-search.js
assets/js/graph.js
assets/js/popover.js
assets/js/util.js
assets/styles/base.scss
layouts/partials/graph.html
layouts/partials/head.html
layouts/partials/katex.html

Everything is in the commits :)

refactor: General performance/style improvements

---

layouts/_default/single.html

> before fix: https://ibb.co/7RTyjs6
> after fix: https://ibb.co/9HgVBgH

fix: fix unicode broken tags

---

content/notes/obsidian.md

In their current form, the two Obsidian settings are described in a bit confusing way. This PR makes the description more accurate.

docs: Clarify Obsidian settings

---

content/notes/showcase.md

thanks for all your work on Quartz Jacky! really enjoying tending my garden!

docs(showcase): adding mwalton to the showcase

---

i18n/fr.toml

small changes for more natural sounding french sentences

i18n: Update fr.toml

---

Dockerfile

Fix `detected dubious ownership in repository at '/quartz'`

---

assets/styles/base.scss

Adds font fallbacks that uses system default fonts when the font isn't available.

Add font fallbacks

---

content/index.md
content/migrating from Quartz 3.md

Feel free to wordsmith however you like. 
Also added a grammar check on the homepage.

Note about existing content at same path on different branches
