assets/darkmode.js, layouts/404.html, layouts/_default/single.html, layouts/index.html, layouts/partials/head.html
Currently, the `darkmode.js` script is loaded after the main content. This means that if you enabled dark mode, you still get a flash of light mode before the script executes and sets it to dark mode. To fix this I've moved the script to the document head. To make that possible I've also had to make some modifications to the script itself, using the `DOMContentLoaded` event to bootstrap the theme toggle switch.
=> Execute darkmode script before first render

assets/styles/base.scss
When a word (or any string without breakpoints (spaces, dashes....), making links the most common place where this becomes an issue) is wider than its container, the text will simply overflow any container, including the viewport. This commit fixes this behavior by making the word-wrap strategy of the browser more aggressive.
Long link before the fix:
The same link after applying this fix:
=> Prevent overflow of long links and words

assets/styles/base.scss, layouts/partials/contact.html
When we put a bunch of `links` inside `data/config.yaml` we can see a horizontal scrolling like this:
This happens because in `layouts/partials/contact.html` the links are generated with no spaces between them.
I managed to solve this adding a `&ZeroWidthSpace;` between each link. Here's how it looks now:
=> make pages more responsive separating contact links with &ZeroWidthSpace;

content/notes/editing.md, layouts/_default/single.html, layouts/index.html
If you have `enableToc: true` in your `data/config.yaml`, you can disable Table of Contents on individual pages by using `enableToc: false` in the page's front matter.
Same intention as #48 but replacing `disableToc: true` with `enableToc: false` to get the same result.
=> disable ToC if the page's front matter has "enableToc: false"

layouts/404.html
Currently it goes to the root, which doesn't work when people have `USERNAME.github.io/MY-DIGITAL-GARDEN`.
=> 404 page: link to home goes to baseURL

content/notes/setup.md
Just an update in the documentation:
(I also removed a duplicated mention to `layouts`)
closes #84
=> docs: warn about possible lost of customization

.github/workflows/deploy.yaml, config.toml
This PR fixes the issue of Last Modified dates not working properly in deployed pages
- Add `fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod` to github actions 
- add date config to `config.yaml`
=> fix: fetch github info

layouts/_default/_markup/render-link.html
Removed strings.TrimRight "/" in line 10 to keep the trailing slash at the end of URLs in regular links. This avoids having every single internal link being a 301 redirect.
=> fix: keep / at end of URL to avoid redirects

assets/js/graph.js, assets/js/search.js, layouts/partials/graph.html
Active nodes will not work if there is a text fragment, particularly one after Cmd-K search
=> Support active node with other data at end of url

assets/js/graph.js, assets/js/router.js, assets/js/search.js, layouts/partials/head.html
Currently, hovering over nodes does nothing. However, hovering over nodes may signify user intention to click soon or click at some other point, so "prefetching" the content and caching it in the background while the user is not navigating is proactively reducing future wait time for page navigations. Prefetching exists by default for `<a>` tags since Million `1.8.x`
This PR implements prefetching for nodes and aborting. By upgrading to Million `1.9.4`, prefetches can be aborted. Prefetches can be problematic when the user does click on a certain node to invoke a real navigation, it may be delayed because of the other prefetches that are occurring. In `1.9.4`, all prefetches are aborted when the user commits to a navigation.  
In the GIF below, you can see that prefetches pop up in the …
=> Prefetch within graph

assets/js/router.js
Introduces `stale-while-revalidate` for SPA navigation, a HTTP cache invalidation strategy popularized by [HTTP RFC 5861](https://tools.ietf.org/html/rfc5861). SWR is a strategy to first return the data from cache (stale), then send the fetch request (revalidate), and finally come with the up-to-date data.
The main advantage of SWR is that Million can now take advantage of using disk cache
=> Bump million to 1.9.6

assets/js/router.js, assets/js/search.js, layouts/partials/head.html
This further removes FOUC by separating the `draw` logic into the `init` and `render` functions. 
`init` renders once on the future DOM, meaning that every time the page is loaded, it is prerendered.
`render` renders every navigation. The reason this exists is because complex logic (like event listeners or side effect logic) cannot be handled by prerendering safely.
The main advantage of this is with latex, which only mutates the DOM without event listeners or side effect logic, allowing it to be safely prerendered and removing the FUOC when viewing latex on SPA mode
=> Remove FOUC from latex rendering

data/config.yaml, layouts/_default/single.html, layouts/partials/github.html
Adds a GitHub edit button beside the Date update text. 
Demo: https://rphla.github.io/garden/+Home/
=> Add GitHub "edit" button

assets/js/clipboard.js
Suggesting this edit to provide a more responsive user experience when copying code successfully.
=> feat: edit the clipboard button to change border colour on success

layouts/partials/textprocessing.html
Internal links would display the subfolder name on my site. I added a line to split the title by "/" and keep the last element, i.e. the name name.
=> feat: Hide full path to file in Wikilinks by default

assets/js/popover.js
If href contains encoded characters (such as í, č, or others), they won't match with the content (since they are not encoded there). The function `decodeURIComponent()` solves this, and makes it possible to use headings such as `# Oxidatívna fosforylácia`.
=> Decode the heading id from split link

assets/styles/base.scss
Not only direct children.
You can see the discrepancy here: https://quartz.jzhao.xyz/
One of these popovers is correctly monospace and another isn't:
versus
Not sure if this is the right change to make to this problem but it looked okay on my fork!
=> fix: Apply monospace style to all meta in a popover

.github/workflows/docker-publish.yaml, Dockerfile, Makefile, content/notes/docker.md, content/notes/editing.md
I created a Dockerfile for an alpine container build of Quartz (as discussed in #211). Upon merging this PR, one can serve Quartz locally at `http://localhost:1313` with the following script:
docker-compose.yml
```
services:
quartz-hugo:
image: ghcr.io/jackyzha0/quartz:hugo
container_name: quartz-hugo
volumes:
- /path/to/quartz:/quartz
ports:
- 1313:1313
environment:
- HUGO_BIND=0.0.0.0
- HUGO_BASEURL=http://localhost
- HUGO_PORT=1313
- HUGO_APPENDPORT=true
```
By default, the container will clone and serve `github:jackyzha0/quartz`. However, one can serve their own fork of `quartz` by cloning to the above `/path/to/quartz` directory.
Then run with: `docker-compose up -d`
One can update their `quartz` fork with: `docker exec -it quartz-hugo make update`.
=> feat: Dockerfile and automated container build

content/notes/config.md, data/config.yaml, layouts/_default/_markup/render-codeblock-mermaid.html, layouts/partials/head.html, layouts/partials/mermaid.html
=> feat: add support for mermaid diagrams

layouts/partials/textprocessing.html
If a non-Markdown file (e.g. PDF or PNG) exists under `content/`, a wikilink to that file will currently render `internal-link broken`, because the existing script assumes it should be a page. I have modified this script to render a direct link to that file in the case that it is not a page.
=> fix: Replacing "internal-link broken" with link to asset

layouts/partials/textprocessing.html
Fixes #176 and a few other issues caused by failure to search for existing notes in situations like:
- File name includes `.`
- File name changed by markdown processor (e.g. `&` into `&amp;` and `'` into `&rsquo;`)
The fix basically:
- attempt to search a file with the `.md` extension
- reverses some of the changes made by typographer
Before:
After:
=> fix edge cases link processing

layouts/partials/textprocessing.html
Hi! I think I found a regex fix for #168. It's probably not the cleanest solution, but it gets the job done. Basically it looks for the first <br> in a callout and break it into two paragraphs.
Say we have the following markdown:
```md
> [!NOTE] Title
> Contents 1
> [!SUMMARY] Title
> 
> Contents 2 as paragraph
> [!info] Title
> 
> hard
> wrap
> [!bug] Title
> hard
> wrap
> [!warning]+ Title
> 
> hard
> wrap
> 
> paragraph
> [!success]- Title
> 
> paragraph
> 
> paragraph
> normal blockquote
> normal blockquote paragraph 1
> 
> normal blockquote paragraph 1
> hard wrap 1
> hard wrap 1
```
Before fix:
After fix:
As far as I can tell, the regex replacement isn't causing other issues, but there could be cases I haven't tested yet.
=> Fix callout behaviour inconsistent with Obsidian (closes #168)

layouts/partials/textprocessing.html
Currently, Quartz embeds all files using the `<img>` tag (which obviously only handles images). Obsidian supports several additional [embedding filetypes](https://help.obsidian.md/Advanced+topics/Accepted+file+formats) for videos, audio, and PDFs.
I've added support for these filetypes with native HTML tags per modality. Simple tests look good on my end!
Note: Anything besides specifically handled filetypes will simply be linked with the `<a>` tag. However, Hugo might not serve this file (since it's not Markdown or known media types). For future consideration.
=> feat: Embedding multimodal assets

assets/js/graph.js
In case someone links a directory where e.g. a list of notes within it is getting shown, the directory's node will be formatted properly.
=> feat: Remove leading slash of folders in graph view

layouts/partials/head.html
When sharing on socials, this change will preview an image, title, and the actual description of the note (if not home/index page).
An example of how Twitter shows it:
=> feat: Adding Twitter and Social image preview including description

layouts/partials/head.html
- I fixed it because the newly added `{{.Site.BaseURL}}icon.png` code added incorrectly to the UI.
- I added code `<meta property="og:description" content="" />` for websites using open graph.
=> fix: Bad UI due to head.html

content/notes/callouts.md
Fixed a dead link and replaced it with a living one.
=> docs: Update link to callouts documentation

assets/js/util.js
> before-fix (with slash) : https://ibb.co/Qr1Dpqp
> after-fix (without slash):  https://ibb.co/w4dD3Nm
=> fix: search highlight not showing because for trailing slash

assets/styles/_callouts.scss
* Fix padding for empty title callouts
Given a callout without title we can see from the picture below that this is the visual resoult:
Instead I've tried to fix this issue, creating this type of padding, which is similar to the case of a callout with a title:
=> fix: padding for empty title callouts

quartz/styles/base.scss
They are either overwritten by something else or don't affect the CSS.
=> Removing redundant properties
